# Generated by Django 5.1.4 on 2026-09-28 19:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capitulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("nombre", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Capítulo",
                "verbose_name_plural": "Capítulos",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("descripcion", models.TextField()),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("ud", "ud"),
                            ("m", "m"),
                            ("m²", "m²"),
                            ("m³", "m³"),
                            ("kg", "kg"),
                            ("h", "h"),
                            ("día", "día"),
                            ("pa", "PA"),
                        ],
                        default="ud",
                        max_length=10,
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas",
                        to="budgets.capitulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
                "ordering": ["orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="PartidaCatalogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("ud", "ud"),
                            ("m", "m"),
                            ("m²", "m²"),
                            ("m³", "m³"),
                            ("kg", "kg"),
                            ("h", "h"),
                            ("día", "día"),
                            ("pa", "PA"),
                        ],
                        default="ud",
                        max_length=10,
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("veces_usada", models.PositiveIntegerField(default=0)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas_catalogo",
                        to="core.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida del catálogo",
                "verbose_name_plural": "Catálogo de partidas",
                "ordering": ["-veces_usada", "descripcion"],
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Se asigna automáticamente al guardar (formato AAAA-NNN).",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("validez_dias", models.PositiveIntegerField(default=30)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviado", "Enviado"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                            ("caducado", "Caducado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "iva_porcentaje",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="10% en reformas de vivienda que cumplen requisitos, 21% en caso general.",
                        max_digits=5,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("enviado_en", models.DateTimeField(blank=True, null=True)),
                ("aceptado_en", models.DateTimeField(blank=True, null=True)),
                ("rechazado_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="projects.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddField(
            model_name="capitulo",
            name="presupuesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capitulos",
                to="budgets.presupuesto",
            ),
        ),
    ]
